# TCL File Generated by Component Editor 17.1
# Wed Jan 17 21:08:24 EST 2018
# DO NOT MODIFY


# 
# bexkat1 "bexkat1" v1.1
#  2018.01.17.21:08:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module bexkat1
# 
set_module_property DESCRIPTION ""
set_module_property NAME bexkat1
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME bexkat1
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bexkat1_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alu_comb.v SYSTEM_VERILOG PATH bexkat1/alu_comb.v
add_fileset_file arbiter.v SYSTEM_VERILOG PATH bexkat1/arbiter.v
add_fileset_file bexkat1.vh SYSTEM_VERILOG_INCLUDE PATH bexkat1/bexkat1.vh
add_fileset_file bexkat1p.v SYSTEM_VERILOG PATH bexkat1/bexkat1p.v TOP_LEVEL_FILE
add_fileset_file exceptions.vh SYSTEM_VERILOG_INCLUDE PATH bexkat1/exceptions.vh
add_fileset_file execute.v SYSTEM_VERILOG PATH bexkat1/execute.v
add_fileset_file fifo.v SYSTEM_VERILOG PATH bexkat1/fifo.v
add_fileset_file hazard.v SYSTEM_VERILOG PATH bexkat1/hazard.v
add_fileset_file idecode.v SYSTEM_VERILOG PATH bexkat1/idecode.v
add_fileset_file ifetch.v SYSTEM_VERILOG PATH bexkat1/ifetch.v
add_fileset_file intcalc.v SYSTEM_VERILOG PATH bexkat1/intcalc.v
add_fileset_file mem.v SYSTEM_VERILOG PATH bexkat1/mem.v
add_fileset_file memwb.v SYSTEM_VERILOG PATH bexkat1/memwb.v
add_fileset_file registerfile.v SYSTEM_VERILOG PATH bexkat1/registerfile.v
add_fileset_file wb.vh SYSTEM_VERILOG_INCLUDE PATH wb.vh


# 
# parameters
# 


# 
# display items
# 

