# TCL File Generated by Component Editor 16.1
# Mon May 08 00:08:24 EDT 2017
# DO NOT MODIFY


# 
# vga "vga" v1.3
# Matt Stock 2017.05.08.00:08:24
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Matt Stock"
set_module_property DISPLAY_NAME vga
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file font8x12.mif MIF PATH vga/font8x12.mif
add_fileset_file fontmem.qip OTHER PATH vga/fontmem.qip
add_fileset_file fontmem.v VERILOG PATH vga/fontmem.v
add_fileset_file graphicsdrv.v VERILOG PATH vga/graphicsdrv.v
add_fileset_file textdrv.v VERILOG PATH vga/textdrv.v
add_fileset_file textlinebuf.qip OTHER PATH vga/textlinebuf.qip
add_fileset_file textlinebuf.v VERILOG PATH vga/textlinebuf.v
add_fileset_file vga_controller.v VERILOG PATH vga/vga_controller.v
add_fileset_file vga_master.v SYSTEM_VERILOG PATH vga/vga_master.v TOP_LEVEL_FILE
add_fileset_file vga_pallette.qip OTHER PATH vga/vga_pallette.qip
add_fileset_file vga_pallette.v VERILOG PATH vga/vga_pallette.v


# 
# parameters
# 
add_parameter VGA_MEMBASE STD_LOGIC_VECTOR 3221225472
set_parameter_property VGA_MEMBASE DEFAULT_VALUE 3221225472
set_parameter_property VGA_MEMBASE DISPLAY_NAME VGA_MEMBASE
set_parameter_property VGA_MEMBASE WIDTH 34
set_parameter_property VGA_MEMBASE TYPE STD_LOGIC_VECTOR
set_parameter_property VGA_MEMBASE UNITS None
set_parameter_property VGA_MEMBASE ALLOWED_RANGES 0:17179869183
set_parameter_property VGA_MEMBASE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_byteenable byteenable Input 4
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_address address Input 10
add_interface_port s0 avs_s0_waitrequest_n waitrequest_n Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_readdata readdata Input 32
add_interface_port m0 avm_m0_byteenable byteenable Output 4
add_interface_port m0 avm_m0_waitrequest_n waitrequest_n Input 1


# 
# connection point vga_out
# 
add_interface vga_out conduit end
set_interface_property vga_out associatedClock ""
set_interface_property vga_out associatedReset reset
set_interface_property vga_out ENABLED true
set_interface_property vga_out EXPORT_OF ""
set_interface_property vga_out PORT_NAME_MAP ""
set_interface_property vga_out CMSIS_SVD_VARIABLES ""
set_interface_property vga_out SVD_ADDRESS_GROUP ""

add_interface_port vga_out coe_vs vs Output 1
add_interface_port vga_out coe_b b Output 8
add_interface_port vga_out coe_blank_n blank_n Output 1
add_interface_port vga_out coe_g g Output 8
add_interface_port vga_out coe_hs hs Output 1
add_interface_port vga_out coe_r r Output 8
add_interface_port vga_out coe_sync_n sync_n Output 1


# 
# connection point vga_clock_in
# 
add_interface vga_clock_in clock end
set_interface_property vga_clock_in clockRate 0
set_interface_property vga_clock_in ENABLED true
set_interface_property vga_clock_in EXPORT_OF ""
set_interface_property vga_clock_in PORT_NAME_MAP ""
set_interface_property vga_clock_in CMSIS_SVD_VARIABLES ""
set_interface_property vga_clock_in SVD_ADDRESS_GROUP ""

add_interface_port vga_clock_in csi_vga_clk clk Input 1


# 
# connection point vga_clock_out
# 
add_interface vga_clock_out clock start
set_interface_property vga_clock_out associatedDirectClock ""
set_interface_property vga_clock_out clockRate 0
set_interface_property vga_clock_out clockRateKnown false
set_interface_property vga_clock_out ENABLED true
set_interface_property vga_clock_out EXPORT_OF ""
set_interface_property vga_clock_out PORT_NAME_MAP ""
set_interface_property vga_clock_out CMSIS_SVD_VARIABLES ""
set_interface_property vga_clock_out SVD_ADDRESS_GROUP ""

add_interface_port vga_clock_out cso_vga_clk clk Output 1

